// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Cafe21_ui_800

#ifndef _CAFE21_UI_800_UI_H
#define _CAFE21_UI_800_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_home
void ui_home_screen_init(void);
extern lv_obj_t *ui_home;
void ui_event_homeLogo( lv_event_t * e);
extern lv_obj_t *ui_homeLogo;
extern lv_obj_t *ui_HomeConfigImage;
extern lv_obj_t *ui_cTitle;
extern lv_obj_t *ui_homeSubTitle;
extern lv_obj_t *ui_homeTitle;
void ui_event_homeButton( lv_event_t * e);
extern lv_obj_t *ui_homeButton;
extern lv_obj_t *ui_homeButtonLabel;
extern lv_obj_t *ui_homeErrorPanel;
extern lv_obj_t *ui_homeErrorIcon;
extern lv_obj_t *ui_homeErrorTitle;
extern lv_obj_t *ui_homeErrorSubTitle;
// CUSTOM VARIABLES

// SCREEN: ui_choose
void ui_choose_screen_init(void);
void ui_event_choose( lv_event_t * e);
extern lv_obj_t *ui_choose;
void ui_event_choosePanelLeft( lv_event_t * e);
extern lv_obj_t *ui_choosePanelLeft;
void ui_event_choosePanel1Button( lv_event_t * e);
extern lv_obj_t *ui_choosePanel1Button;
extern lv_obj_t *ui_choosePanel1ButtonLabel;
extern lv_obj_t *ui_choosePanel1Title;
extern lv_obj_t *ui_choosePanel1Image;
extern lv_obj_t *ui_choosePanel1PriceLabel;
extern lv_obj_t *ui_choosePanel1PriceContainerTop;
extern lv_obj_t *ui_choosePanel1PriceSats;
extern lv_obj_t *ui_choosePanel1PriceBrl;
extern lv_obj_t *ui_choosePanel1PriceContainerBottom;
void ui_event_choosePanelRight( lv_event_t * e);
extern lv_obj_t *ui_choosePanelRight;
void ui_event_primaryButton2( lv_event_t * e);
extern lv_obj_t *ui_primaryButton2;
extern lv_obj_t *ui_pbLabel2;
extern lv_obj_t *ui_choosePanel2Title;
extern lv_obj_t *ui_choosePanel2Image;
extern lv_obj_t *ui_choosePanel2PriceLabel;
extern lv_obj_t *ui_choosePanel2PriceContainerTop;
extern lv_obj_t *ui_choosePanel2PriceSats;
extern lv_obj_t *ui_choosePanel2PriceBrl;
extern lv_obj_t *ui_choosePanel2PriceContainerBottom;
void ui_event_chooseBackImage_goBack( lv_event_t * e);
extern lv_obj_t *ui_chooseBackImage;
void ui_event_chooseLogo( lv_event_t * e);
extern lv_obj_t *ui_chooseLogo;
// CUSTOM VARIABLES

// SCREEN: ui_payment
void ui_payment_screen_init(void);
void ui_event_payment( lv_event_t * e);
extern lv_obj_t *ui_payment;
extern lv_obj_t *ui_paymentSubTitle;
extern lv_obj_t *ui_paymentTitle;
void ui_event_paymentBackImage( lv_event_t * e);
extern lv_obj_t *ui_paymentBackImage;
void ui_event_paymentLogo( lv_event_t * e);
extern lv_obj_t *ui_paymentLogo;
extern lv_obj_t *ui_qrCodeContainer;
// CUSTOM VARIABLES

// SCREEN: ui_preparing
void ui_preparing_screen_init(void);
void ui_event_preparing( lv_event_t * e);
extern lv_obj_t *ui_preparing;
extern lv_obj_t *ui_preparingPanel;
void ui_event_preparingButton( lv_event_t * e);
extern lv_obj_t *ui_preparingButton;
extern lv_obj_t *ui_preparingButtonLabel;
extern lv_obj_t *ui_preparingTitle;
extern lv_obj_t *ui_preparingImage;
extern lv_obj_t *ui_bcPrepIcon;
extern lv_obj_t *ui_preparingProgress;
void ui_event_preparingLogo2( lv_event_t * e);
extern lv_obj_t *ui_preparingLogo2;
// CUSTOM VARIABLES

// SCREEN: ui_successLogo
void ui_successLogo_screen_init(void);
void ui_event_successLogo( lv_event_t * e);
extern lv_obj_t *ui_successLogo;
void ui_event_successEndImage( lv_event_t * e);
extern lv_obj_t *ui_successEndImage;
extern lv_obj_t *ui_successPanel;
void ui_event_successPanelButton( lv_event_t * e);
extern lv_obj_t *ui_successPanelButton;
extern lv_obj_t *ui_successPanelButtonLabel;
extern lv_obj_t *ui_successPanelTitle;
extern lv_obj_t *ui_successPanelImage;
extern lv_obj_t *ui_logoSuccess;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_logo21_png);   // assets/logo21.png
LV_IMG_DECLARE( ui_img_configsmall_png);   // assets/configSmall.png
LV_IMG_DECLARE( ui_img_watersmall_png);   // assets/waterSmall.png
LV_IMG_DECLARE( ui_img_expressolarge_png);   // assets/expressoLarge.png
LV_IMG_DECLARE( ui_img_coffelarge_png);   // assets/coffeLarge.png
LV_IMG_DECLARE( ui_img_chevronsmall_png);   // assets/chevronSmall.png
LV_IMG_DECLARE( ui_img_exitsmall_png);   // assets/exitSmall.png
LV_IMG_DECLARE( ui_img_checklarge_png);   // assets/checkLarge.png
LV_IMG_DECLARE( ui_img_419703364);   // assets/Property 1=Wi-Fi.png
LV_IMG_DECLARE( ui_img_qr_code_png);   // assets/QR Code.png
LV_IMG_DECLARE( ui_img_hoselarge_png);   // assets/hoseLarge.png
LV_IMG_DECLARE( ui_img_minussmall_png);   // assets/minusSmall.png
LV_IMG_DECLARE( ui_img_plussmall_png);   // assets/plusSmall.png
LV_IMG_DECLARE( ui_img_showerlarge_png);   // assets/showerLarge.png
LV_IMG_DECLARE( ui_img_toogleoff_png);   // assets/toogleOff.png
LV_IMG_DECLARE( ui_img_toogleon_png);   // assets/toogleOn.png
LV_IMG_DECLARE( ui_img_trashsmall_png);   // assets/trashSmall.png
LV_IMG_DECLARE( ui_img_warnsmall_png);   // assets/warnSmall.png
LV_IMG_DECLARE( ui_img_xlarge_png);   // assets/xLarge.png

// FONTS
LV_FONT_DECLARE( ui_font_LoraRegula24);
LV_FONT_DECLARE( ui_font_LoraRegula40);
LV_FONT_DECLARE( ui_font_LoraRegula64);
LV_FONT_DECLARE( ui_font_OpenSansBold14);
LV_FONT_DECLARE( ui_font_OpenSansBold20);
LV_FONT_DECLARE( ui_font_OpenSansRegular14);
LV_FONT_DECLARE( ui_font_OpenSansRegular16);
LV_FONT_DECLARE( ui_font_OpenSansRegular20);
LV_FONT_DECLARE( ui_font_OpenSansSemiBold14);
LV_FONT_DECLARE( ui_font_OpenSansSemiBold16);
LV_FONT_DECLARE( ui_font_OpenSansSemiBold20);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
