// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Cafe21_ui_800

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void chooseButton1Clicked(lv_event_t * e);
void chooseButton2Clicked(lv_event_t * e);
void chooseBackButtonClicked(lv_event_t * e);
void paymentBackButtonClicked(lv_event_t * e);
void preparingCancelButtonClicked(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
