// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Cafe21_ui_480

#include "ui.h"
#include "ui_helpers.h"
#include "ui_extended.h"
char ui_action;
///////////////////// VARIABLES ////////////////////


// SCREEN: ui_hero
void ui_hero_screen_init(void);
lv_obj_t * ui_hero;
void ui_event_logo21(lv_event_t * e);
lv_obj_t * ui_logo21;
lv_obj_t * ui_gear;
lv_obj_t * ui_cTitle;
lv_obj_t * ui_subtitulo;
lv_obj_t * ui_titulo;
void ui_event_primaryButton(lv_event_t * e);
lv_obj_t * ui_primaryButton;
lv_obj_t * ui_pbLabel;
lv_obj_t * ui_errorPanel;
lv_obj_t * ui_erroIcon;
lv_obj_t * ui_errorMessage;
lv_obj_t * ui_errorDescription;


// SCREEN: ui_choseCoffe
void ui_choseCoffe_screen_init(void);
void ui_event_choseCoffe(lv_event_t * e);
lv_obj_t * ui_choseCoffe;
void ui_event_ePanel(lv_event_t * e);
lv_obj_t * ui_ePanel;
void ui_event_primaryButton1(lv_event_t * e);
lv_obj_t * ui_primaryButton1;
lv_obj_t * ui_pbLabel1;
lv_obj_t * ui_eTitle;
lv_obj_t * ui_expressoOrder;
lv_obj_t * ui_ePrLabel;
lv_obj_t * ui_eConteiner;
lv_obj_t * ui_eSats;
lv_obj_t * ui_eReal;
lv_obj_t * ui_eConteiner3;
void ui_event_cPanel(lv_event_t * e);
lv_obj_t * ui_cPanel;
void ui_event_primaryButton2(lv_event_t * e);
lv_obj_t * ui_primaryButton2;
lv_obj_t * ui_pbLabel2;
lv_obj_t * ui_bcTitle;
lv_obj_t * ui_coffeOrder;
lv_obj_t * ui_cPrLabel;
lv_obj_t * ui_cConteiner;
lv_obj_t * ui_cSats;
lv_obj_t * ui_cReal;
lv_obj_t * ui_cConteiner2;
lv_obj_t * ui_goBack;


// SCREEN: ui_payment
void ui_payment_screen_init(void);
void ui_event_payment(lv_event_t * e);
lv_obj_t * ui_payment;
lv_obj_t * ui_pagueSubLabel;
lv_obj_t * ui_pagueLabel;
lv_obj_t * ui_qrCode;
void ui_event_goBack2(lv_event_t * e);
lv_obj_t * ui_goBack2;


// SCREEN: ui_preparing
void ui_preparing_screen_init(void);
void ui_event_preparing(lv_event_t * e);
lv_obj_t * ui_preparing;
lv_obj_t * ui_ePanel1;
void ui_event_btnCancel(lv_event_t * e);
lv_obj_t * ui_btnCancel;
lv_obj_t * ui_btnCancelLabel;
lv_obj_t * ui_prepLabel;
lv_obj_t * ui_ePrepIcon;
lv_obj_t * ui_bcPrepIcon;
lv_obj_t * ui_Bar1;


// SCREEN: ui_success
void ui_success_screen_init(void);
void ui_event_success(lv_event_t * e);
lv_obj_t * ui_success;
void ui_event_goBack3(lv_event_t * e);
lv_obj_t * ui_goBack3;
lv_obj_t * ui_ePanel2;
void ui_event_btnCancel1(lv_event_t * e);
lv_obj_t * ui_btnCancel1;
lv_obj_t * ui_btnCancelLabel1;
lv_obj_t * ui_prepLabel1;
lv_obj_t * ui_ePrepIcon1;
lv_obj_t * ui_logoSuccess;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_logo[1] = {&ui_img_logo21_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_logo21(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_choseCoffe, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_choseCoffe_screen_init);
        ui_action = 6;
    }
}
void ui_event_hero_loading(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    // ui_action = 4;
}

void ui_event_primaryButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_choseCoffe, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_choseCoffe_screen_init);
    }
}
void ui_event_choseCoffe(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_hero, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_hero_screen_init);
    }
}
void ui_event_ePanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_payment, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_payment_screen_init);
    }
}
void ui_event_primaryButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_payment, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_payment_screen_init);
        ui_action = 1;
    }
}
void ui_event_cPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_payment, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_payment_screen_init);
    }
}
void ui_event_primaryButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_payment, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_payment_screen_init);
        ui_action = 2;
    }
}
void ui_event_payment(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_hero, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_hero_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_preparing, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_preparing_screen_init);
        ui_action = 6;
    }
}
void ui_event_goBack2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_choseCoffe, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_choseCoffe_screen_init);
    }
}
void ui_event_preparing(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_hero, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_hero_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_success, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_success_screen_init);
    }
}
void ui_event_btnCancel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_hero, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_hero_screen_init);
    }
}
void ui_event_success(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_hero, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_hero_screen_init);
    }
}
void ui_event_goBack3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_hero, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_hero_screen_init);
    }
}
void ui_event_btnCancel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_hero, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0, &ui_hero_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_hero_screen_init();
    ui_choseCoffe_screen_init();
    ui_payment_screen_init();
    ui_preparing_screen_init();
    ui_success_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_hero);
}
