// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Cafe21UI320

#include "../ui.h"

void ui_payment_screen_init(void)
{
ui_payment = lv_obj_create(NULL);
lv_obj_set_style_bg_color(ui_payment, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_payment, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_qrCodeContainer = lv_obj_create(ui_payment);
lv_obj_remove_style_all(ui_qrCodeContainer);
lv_obj_set_width( ui_qrCodeContainer, 220);
lv_obj_set_height( ui_qrCodeContainer, 220);
lv_obj_set_x( ui_qrCodeContainer, 104 );
lv_obj_set_y( ui_qrCodeContainer, 0 );
lv_obj_set_align( ui_qrCodeContainer, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_qrCodeContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_qrCodeContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_qrCodeContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_paymentPanel = lv_obj_create(ui_payment);
lv_obj_set_width( ui_paymentPanel, 180);
lv_obj_set_height( ui_paymentPanel, 158);
lv_obj_set_x( ui_paymentPanel, -273 );
lv_obj_set_y( ui_paymentPanel, -80 );
lv_obj_set_align( ui_paymentPanel, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_clear_flag( ui_paymentPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_paymentPanel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_paymentPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_paymentPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_paymentPanel, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_paymentPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_paymentPanel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_paymentPanel, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_paymentPanel, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_paymentPanel, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_paymentPanel, 12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_paymentTitle = lv_label_create(ui_paymentPanel);
lv_obj_set_width( ui_paymentTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_paymentTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_paymentTitle, 8 );
lv_obj_set_y( ui_paymentTitle, 22 );
lv_label_set_text(ui_paymentTitle,"Pague seu Café");
lv_obj_set_style_text_color(ui_paymentTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_paymentTitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_paymentTitle, &ui_font_LoraRegular20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_paymentSubtitle = lv_label_create(ui_paymentPanel);
lv_obj_set_width( ui_paymentSubtitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_paymentSubtitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_paymentSubtitle, 8 );
lv_obj_set_y( ui_paymentSubtitle, -17 );
lv_obj_set_align( ui_paymentSubtitle, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_paymentSubtitle,"Seu café veloz\nMinerado num raio\nPronto num instante");
lv_obj_set_style_text_color(ui_paymentSubtitle, lv_color_hex(0x999999), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_paymentSubtitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_paymentSubtitle, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_paymentSubtitle, &ui_font_OpenSansSemiBold12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_paymentBackButton = lv_imgbtn_create(ui_payment);
lv_imgbtn_set_src(ui_paymentBackButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_chevron_png, NULL);
lv_imgbtn_set_src(ui_paymentBackButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_chevron_png, NULL);
lv_obj_set_width( ui_paymentBackButton, 32);
lv_obj_set_height( ui_paymentBackButton, 32);
lv_obj_set_x( ui_paymentBackButton, -212 );
lv_obj_set_y( ui_paymentBackButton, -134 );
lv_obj_set_align( ui_paymentBackButton, LV_ALIGN_CENTER );

ui_qrCodeLogo = lv_img_create(ui_payment);
lv_img_set_src(ui_qrCodeLogo, &ui_img_logo21_png);
lv_obj_set_width( ui_qrCodeLogo, 42);
lv_obj_set_height( ui_qrCodeLogo, 42);
lv_obj_set_x( ui_qrCodeLogo, 323 );
lv_obj_set_y( ui_qrCodeLogo, 139 );
lv_obj_add_flag( ui_qrCodeLogo, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_qrCodeLogo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_qrCodeLogo, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_qrCodeLogo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_qrCodeLogo, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_qrCodeLogo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_qrCodeLogo, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_qrCodeLogo, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_paymentBackButton, ui_event_paymentBackButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_payment, ui_event_payment, LV_EVENT_ALL, NULL);

}
