// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Cafe21UI320

#include "../ui.h"

void ui_preparing_screen_init(void)
{
ui_preparing = lv_obj_create(NULL);
lv_obj_set_style_bg_color(ui_preparing, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_preparing, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_preparingPanel = lv_obj_create(ui_preparing);
lv_obj_set_width( ui_preparingPanel, 218);
lv_obj_set_height( ui_preparingPanel, 210);
lv_obj_set_align( ui_preparingPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_preparingPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_preparingPanel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_preparingPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_preparingPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_preparingPanel, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_preparingPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_preparingPanel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_preparingPanel, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_preparingPanel, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_preparingPanel, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_preparingPanel, 16, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_preparingPanel, 12, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_preparingPanel, 12, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_preparingPanel, 12, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_preparingPanel, 12, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_preparingCancelButton = lv_btn_create(ui_preparingPanel);
lv_obj_set_width( ui_preparingCancelButton, 194);
lv_obj_set_height( ui_preparingCancelButton, 36);
lv_obj_set_x( ui_preparingCancelButton, 0 );
lv_obj_set_y( ui_preparingCancelButton, 10 );
lv_obj_set_align( ui_preparingCancelButton, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_preparingCancelButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_preparingCancelButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_preparingCancelButton, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_preparingCancelButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_preparingCancelButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_preparingCancelButton, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_preparingCancelButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_preparingCancelButton, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_preparingCancelButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_preparingCancelButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_preparingCancelButton, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_preparingCancelButton, &ui_font_OpenSansBold14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_preparingCancelButtonLabel = lv_label_create(ui_preparingCancelButton);
lv_obj_set_width( ui_preparingCancelButtonLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_preparingCancelButtonLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_preparingCancelButtonLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_preparingCancelButtonLabel,"Cancelar");
lv_obj_set_style_text_color(ui_preparingCancelButtonLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_preparingCancelButtonLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_preparingCancelButtonLabel, &ui_font_OpenSansBold14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_preparingLabel = lv_label_create(ui_preparingPanel);
lv_obj_set_width( ui_preparingLabel, 194);
lv_obj_set_height( ui_preparingLabel, 44);
lv_obj_set_x( ui_preparingLabel, 0 );
lv_obj_set_y( ui_preparingLabel, 72 );
lv_obj_set_align( ui_preparingLabel, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_preparingLabel,"Saindo um\nEspresso to the Moon");
lv_obj_set_style_text_color(ui_preparingLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_preparingLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_preparingLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_preparingLabel, &ui_font_LoraRegular14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_preparingImage = lv_img_create(ui_preparingPanel);
lv_img_set_src(ui_preparingImage, &ui_img_espresso_png);
lv_obj_set_width( ui_preparingImage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_preparingImage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_preparingImage, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_preparingImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_preparingImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_preparingProgress = lv_bar_create(ui_preparingPanel);
lv_bar_set_value(ui_preparingProgress,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_preparingProgress, 25, LV_ANIM_OFF);
lv_obj_set_width( ui_preparingProgress, 194);
lv_obj_set_height( ui_preparingProgress, 6);
lv_obj_set_x( ui_preparingProgress, 0 );
lv_obj_set_y( ui_preparingProgress, lv_pct(74) );
lv_obj_set_align( ui_preparingProgress, LV_ALIGN_TOP_MID );
lv_obj_set_style_bg_color(ui_preparingProgress, lv_color_hex(0x474747), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_preparingProgress, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_preparingProgress, 4, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_preparingProgress, lv_color_hex(0xD9D9D9), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_preparingProgress, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_preparingLogo = lv_img_create(ui_preparing);
lv_img_set_src(ui_preparingLogo, &ui_img_logo21_png);
lv_obj_set_width( ui_preparingLogo, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_preparingLogo, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_preparingLogo, 436 );
lv_obj_set_y( ui_preparingLogo, 12 );
lv_obj_add_flag( ui_preparingLogo, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_preparingLogo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_preparingCancelButton, ui_event_preparingCancelButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_preparing, ui_event_preparing, LV_EVENT_ALL, NULL);

}
