// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Cafe21UI800

#include "../ui.h"

void ui_payment_screen_init(void)
{
ui_payment = lv_obj_create(NULL);
lv_obj_set_style_bg_color(ui_payment, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_payment, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_paymentBack = lv_imgbtn_create(ui_payment);
lv_imgbtn_set_src(ui_paymentBack, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_chevron_png, NULL);
lv_imgbtn_set_src(ui_paymentBack, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_chevron_png, NULL);
lv_obj_set_width( ui_paymentBack, 48);
lv_obj_set_height( ui_paymentBack, 48);
lv_obj_set_x( ui_paymentBack, -352 );
lv_obj_set_y( ui_paymentBack, -200 );
lv_obj_set_align( ui_paymentBack, LV_ALIGN_CENTER );

ui_paymentPanel = lv_obj_create(ui_payment);
lv_obj_set_width( ui_paymentPanel, 324);
lv_obj_set_height( ui_paymentPanel, 263);
lv_obj_set_x( ui_paymentPanel, -223 );
lv_obj_set_y( ui_paymentPanel, 2 );
lv_obj_set_align( ui_paymentPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_paymentPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_paymentPanel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_paymentPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_paymentPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_paymentPanel, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_paymentPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_paymentTitle = lv_label_create(ui_paymentPanel);
lv_obj_set_width( ui_paymentTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_paymentTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_paymentTitle, 0 );
lv_obj_set_y( ui_paymentTitle, 28 );
lv_obj_set_align( ui_paymentTitle, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_paymentTitle,"Pague seu Café");
lv_obj_set_style_text_color(ui_paymentTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_paymentTitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_paymentTitle, &ui_font_LoraRegular40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_paymentSubTitle = lv_label_create(ui_paymentPanel);
lv_obj_set_width( ui_paymentSubTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_paymentSubTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_paymentSubTitle, -46 );
lv_obj_set_y( ui_paymentSubTitle, 110 );
lv_obj_set_align( ui_paymentSubTitle, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_paymentSubTitle,"Seu café veloz\nMinerado num raio\nPronto num instante");
lv_obj_set_style_text_color(ui_paymentSubTitle, lv_color_hex(0x999999), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_paymentSubTitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_paymentSubTitle, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_paymentSubTitle, &ui_font_OpenSansRegular20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_qrCodeContainer = lv_obj_create(ui_payment);
lv_obj_remove_style_all(ui_qrCodeContainer);
lv_obj_set_width( ui_qrCodeContainer, 408);
lv_obj_set_height( ui_qrCodeContainer, 408);
lv_obj_set_x( ui_qrCodeContainer, 158 );
lv_obj_set_y( ui_qrCodeContainer, -1 );
lv_obj_set_align( ui_qrCodeContainer, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_qrCodeContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_qrCodeContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_qrCodeContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_paymentLogo = lv_img_create(ui_payment);
lv_img_set_src(ui_paymentLogo, &ui_img_logo21_png);
lv_obj_set_width( ui_paymentLogo, LV_SIZE_CONTENT);  /// 48
lv_obj_set_height( ui_paymentLogo, LV_SIZE_CONTENT);   /// 48
lv_obj_set_x( ui_paymentLogo, 524 );
lv_obj_set_y( ui_paymentLogo, 204 );
lv_obj_add_flag( ui_paymentLogo, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_paymentLogo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_paymentLogo, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_paymentLogo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_paymentLogo, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_paymentLogo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_paymentLogo, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_paymentLogo, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_paymentBack, ui_event_paymentBack, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_paymentLogo, ui_event_paymentLogo, LV_EVENT_ALL, NULL);

}
