// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Cafe21_ui_800

#include "../ui.h"

void ui_payment_screen_init(void)
{
ui_payment = lv_obj_create(NULL);
lv_obj_set_style_bg_color(ui_payment, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_payment, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_paymentSubTitle = lv_label_create(ui_payment);
lv_obj_set_width( ui_paymentSubTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_paymentSubTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_paymentSubTitle, 0 );
lv_obj_set_y( ui_paymentSubTitle, 400 );
lv_obj_set_align( ui_paymentSubTitle, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_paymentSubTitle,"Seu café será minerado em segundos,\napós a confirmação do pagamento. ");
lv_obj_set_style_text_color(ui_paymentSubTitle, lv_color_hex(0x999999), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_paymentSubTitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_paymentSubTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_paymentSubTitle, &ui_font_OpenSansRegular20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_paymentTitle = lv_label_create(ui_payment);
lv_obj_set_width( ui_paymentTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_paymentTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_paymentTitle, 0 );
lv_obj_set_y( ui_paymentTitle, 334 );
lv_obj_set_align( ui_paymentTitle, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_paymentTitle,"Pague seu Café");
lv_obj_set_style_text_color(ui_paymentTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_paymentTitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_paymentTitle, &ui_font_LoraRegula40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_paymentBackImage = lv_imgbtn_create(ui_payment);
lv_imgbtn_set_src(ui_paymentBackImage, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_chevronsmall_png, NULL);
lv_imgbtn_set_src(ui_paymentBackImage, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_chevronsmall_png, NULL);
lv_obj_set_height( ui_paymentBackImage, 48);
lv_obj_set_width( ui_paymentBackImage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_paymentBackImage, 24 );
lv_obj_set_y( ui_paymentBackImage, 16 );

ui_paymentLogo = lv_img_create(ui_payment);
lv_img_set_src(ui_paymentLogo, &ui_img_logo21_png);
lv_obj_set_width( ui_paymentLogo, LV_SIZE_CONTENT);  /// 48
lv_obj_set_height( ui_paymentLogo, LV_SIZE_CONTENT);   /// 48
lv_obj_set_x( ui_paymentLogo, 728 );
lv_obj_set_y( ui_paymentLogo, 16 );
lv_obj_add_flag( ui_paymentLogo, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_paymentLogo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_qrCodeContainer = lv_obj_create(ui_payment);
lv_obj_remove_style_all(ui_qrCodeContainer);
lv_obj_set_width( ui_qrCodeContainer, 256);
lv_obj_set_height( ui_qrCodeContainer, 256);
lv_obj_set_x( ui_qrCodeContainer, 0 );
lv_obj_set_y( ui_qrCodeContainer, -48 );
lv_obj_set_align( ui_qrCodeContainer, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_qrCodeContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_paymentBackImage, ui_event_paymentBackImage, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_paymentLogo, ui_event_paymentLogo, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_payment, ui_event_payment, LV_EVENT_ALL, NULL);

}
