// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Cafe21_ui_800

#ifndef _UI_COMP_GOBACK_H
#define _UI_COMP_GOBACK_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT goBack
#define UI_COMP_GOBACK_GOBACK 0
#define _UI_COMP_GOBACK_NUM 1
lv_obj_t *ui_goBack_create(lv_obj_t *comp_parent);
void ui_event_comp_goBack_goBack( lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
