// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Cafe21UI480

#include "../ui.h"

void ui_success_screen_init(void)
{
ui_success = lv_obj_create(NULL);
lv_obj_set_style_bg_color(ui_success, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_success, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_sucessLogo = lv_img_create(ui_success);
lv_img_set_src(ui_sucessLogo, &ui_img_logo21_png);
lv_obj_set_width( ui_sucessLogo, LV_SIZE_CONTENT);  /// 48
lv_obj_set_height( ui_sucessLogo, LV_SIZE_CONTENT);   /// 48
lv_obj_set_x( ui_sucessLogo, 436 );
lv_obj_set_y( ui_sucessLogo, 12 );
lv_obj_add_flag( ui_sucessLogo, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_sucessLogo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_successPanel = lv_obj_create(ui_success);
lv_obj_set_width( ui_successPanel, 218);
lv_obj_set_height( ui_successPanel, 210);
lv_obj_set_align( ui_successPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_successPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_successPanel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_successPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_successPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_successPanel, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_successPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_successPanel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_successPanel, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_successPanel, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_successPanel, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_successPanel, 16, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_successPanel, 12, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_successPanel, 12, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_successPanel, 12, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_successPanel, 12, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_successPanelButton = lv_btn_create(ui_successPanel);
lv_obj_set_width( ui_successPanelButton, 194);
lv_obj_set_height( ui_successPanelButton, 36);
lv_obj_set_x( ui_successPanelButton, 0 );
lv_obj_set_y( ui_successPanelButton, 10 );
lv_obj_set_align( ui_successPanelButton, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_successPanelButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_successPanelButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_successPanelButton, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_successPanelButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_successPanelButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_successPanelButton, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_successPanelButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_successPanelButton, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_successPanelButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_successPanelButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_successPanelButton, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_successPanelButton, &ui_font_OpenSansBold14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_successPanelButtonLabel = lv_label_create(ui_successPanelButton);
lv_obj_set_width( ui_successPanelButtonLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_successPanelButtonLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_successPanelButtonLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_successPanelButtonLabel,"Finalizar (10s)");
lv_obj_set_style_text_color(ui_successPanelButtonLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_successPanelButtonLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_successPanelButtonLabel, &ui_font_OpenSansBold14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_successPanelTitle = lv_label_create(ui_successPanel);
lv_obj_set_width( ui_successPanelTitle, 194);
lv_obj_set_height( ui_successPanelTitle, 44);
lv_obj_set_x( ui_successPanelTitle, 0 );
lv_obj_set_y( ui_successPanelTitle, 72 );
lv_obj_set_align( ui_successPanelTitle, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_successPanelTitle,"Aproveite seu\nEspresso to the Moon");
lv_obj_set_style_text_color(ui_successPanelTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_successPanelTitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_successPanelTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_successPanelTitle, &ui_font_LoraRegular14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_sucessPanelImage = lv_img_create(ui_successPanel);
lv_img_set_src(ui_sucessPanelImage, &ui_img_check_png);
lv_obj_set_width( ui_sucessPanelImage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_sucessPanelImage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_sucessPanelImage, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_sucessPanelImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_sucessPanelImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_successPanelButton, ui_event_successPanelButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_success, ui_event_success, LV_EVENT_ALL, NULL);

}
